const { Schema, model } = require("mongoose");

const productSchema = new Schema(
  {
    // _id is autogenerated by mongoDB for each entry
    name: {
      type: String,
      required: [true, "A product must have a name"],
    },
    desc: {
      type: String,
      required: [true, "A product must have a description"],
    },
    SKU: {
      type: String,
      required: [true, "A product must have a SKU"],
    },
    category_id: {
      type: Schema.Types.ObjectId,
      ref: "Category",
    },
    inventory_id: {
      type: Schema.Types.ObjectId,
      ref: "Inventory",
    },
    price: {
      type: Number,
      required: [true, "A product must have a price"],
    },
    discount_id: {
      type: Schema.Types.ObjectId,
      ref: "Discount",
    },
    deleted_at: {
      type: Date,
      default: null,
    },
  },
  { timestamps: true } // this will automatically create and manage created_at and modifed_at
);

const productCategorySchema = new Schema(
  {
    name: {
      type: String,
      required: [true, "A category must have a name"],
      unique: true,
    },
    desc: {
      type: String,
    },
    deleted_at: {
      type: Date,
      default: null,
    },
  },
  { timestamps: true } // this will automatically create and manage created_at and modifed_at
);

const inventorySchema = new Schema(
  {
    quantity: {
      type: Number,
      required: [true, "Inventory must have a stock level"],
    },
    deleted_at: {
      type: Date,
      default: null,
    },
  },
  { timestamps: true } // this will automatically create and manage created_at and modifed_at
);

const discountSchema = new Schema(
  {
    name: {
      type: String,
      required: [true, "Discount must have a name"],
    },
    desc: {
      type: String,
      required: [true, "Discount must have a description"],
    },
    discount_percent: {
      type: Number,
      required: [true, "Discount must have a percentage"],
    },
    active: {
      type: Boolean,
      default: true,
    },
    deleted_at: {
      type: Date,
      default: null,
    },
  },
  { timestamps: true } // this will automatically create and manage created_at and modifed_at
);
const Category = model("Category", categorySchema);
const Inventory = model("Inventory", inventorySchema);
const Discount = model("Discount", discountSchema);
const Product = model("Product", productSchema);

module.exports = { Category, Inventory, Discount, Product };
